language: node_js
node_js:
  - node # uses most recent stable node version
services:
  - postgresql # starts up postgres
addons:
  postgresql: '9.6' # highest available postgres version on Travis
dist: trusty # uses trusty environment
sudo: false # when on trusty, uses Docker containers for speed
notifications:
  email:
    on_success: change # default: change (only when going from broken to fixed)
    on_failure: always # default: always (which is annoying, as it should be)
install:
  - npm ci # faster, goes only from package-lock
before_script:
  - psql -c 'create database "boilermaker-test";' -U postgres # remember to change this name if you change it elsewhere (e.g. package.json)

before_deploy:
  - npm run build-client # make the bundle
  - rm -rf node_modules # omit from the tarball, since we skip cleanup
deploy:
  skip_cleanup: true # prevents travis from deleting the build
  provider: heroku
  app: 'producks' # see README
  api_key:
    secure: 'V3RecUHtvS8vPkO9SPPyC/vBNxpxG60VC9155K4xmSQSuNUQrY7AHj48e4jloXVxufoR5vL6su8buXe01NYSxJ/uOug7MkTwvLZJowVgfFnhx8+cfMqUA1i7W3xY7Dwqz9kRWed6m/Wz8uvwoDz9He+DFgf11rC/FZ85Le5o8Fbn/rnQXRsHZF7uuE5+/GvSMPA7W45WxzvGO4Nhl7g6v6Izxf+eqBzgAV9N1ubI+UJooMJXw948Hp0WsZecZL/y6LtpuwfEHebHtmq7JKhr2Z9NtQzHlcb4b8HchbV4jL47K/rLTOEl1yHcuguW9Bw7oHIlcTvixq6LUn+ufhkxCAY5ht9T3wmKv+fyKjOnVb0J5D03EQcyTVGKYHaXycyju+MHNuqHc7J7/VYpNZ6dEfaQMvE8/9G2ZwckprcpKCiRE+yInSo61185AdawrCFG+Bz7YWjJxB8UnL2ipEI3Lp2aJK2fj5qRSaQFbZlHrbfN7NzHEBldVWR+PWFZ+BIdOqfzTRcEL1SPl7CDlx1/EAURG7kGEBhAVOudJu4ypYkvCFZtlcjkNPl9kD1GyjeMBQC9hLnEyszeykrhZXmhBfCpr2nbte04ta7BtuLuZw1cRJqxjSGjc8GT+LMh6r8XCMtXLyEsKMQ+tz+fAPzsTcvSCJlSjE+af4Ui5vjaVXc='
#random test
